### ISSUE TITLE
Issue in Xcode

### ISSUE THREAD

**Issue by savadmv** [peerwaya/flutter_voip_push_notification#4]
**No such module 'flutter_voip_push_notification'**

I get this error in Xcode. 

<img width="623" alt="Screen Shot 2020-05-27 at 5 57 34 PM" src="https://user-images.githubusercontent.com/34649362/83019208-307dea00-a044-11ea-8916-d130e869b313.png">

**Comment by hoangphamw** [comment]
I used `flutter build ios`  or `flutter run` to solve problem

**Comment by savadmv** [comment]
Thank you @hoangphamw  . It worked
