### ISSUE TITLE
Can't get notification due to `BadDeviceToken` 

### ISSUE THREAD

**Issue by wakkihaya** [peerwaya/flutter_voip_push_notification#9]
Through this plugin, I could get device token. But, I couldn't somehow get voip push notification by the token. Every time I tried to send push notification with the token by using `curl` command or Amazon SNS, I got error `{reason: BadDeviceToken}` .
(
```
curl --http2     -E voip_services.pem     --header "apns-topic: com.herelabs.app.voip"     -d "{\"message\":\"Hello\"}"     https://api.push.apple.com/3/device/{devicetoken}
```
)

My readiness for voip push notification is here: 
- VoIP certificate(Production & Sandbox)
- Ad hoc provision
- iOS 14 ( real device)
- Check `Voice over IP` , `Remote notification` in info.plist.

And what I tried is:
-  Delete app cache in real device and reinstall it
- Check if my environment is correct according to [this thread](https://stackoverflow.com/questions/42511476/what-are-the-possible-reasons-to-get-apns-responses-baddevicetoken-or-unregister).

Does anyone know why this happens? 
Thank you

**Comment by JayPerfetto** [comment]
What was your resolution?

**Comment by nerdsarena** [comment]
same issue with me :(
